services:
  gatekeeper:
    image: ghcr.io/nayetdet/gatekeeper:latest
    init: true
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=${CRON?err}
        - swarm.cronjob.skip-running=true
        - swarm.cronjob.registry-auth=true
        - swarm.cronjob.query-registry=true
      restart_policy:
        condition: none
      resources:
        limits:
          memory: 4G
    volumes:
      - type: bind
        source: ./data
        target: /app/data
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 2147483648 # ~2G
    environment:
      TZ: ${TZ}
      BROWSER_HEADLESS: ${BROWSER_HEADLESS}
      EPIC_GAMES_EMAIL: ${EPIC_GAMES_EMAIL}
      EPIC_GAMES_PASSWORD: ${EPIC_GAMES_PASSWORD}
      EPIC_GAMES_LOCALE: ${EPIC_GAMES_LOCALE}
      EPIC_GAMES_COUNTRY: ${EPIC_GAMES_COUNTRY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      TELEGRAM_BOT_ENABLED: ${TELEGRAM_BOT_ENABLED}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_CHAT_ID: ${TELEGRAM_BOT_CHAT_ID}

  gatekeeper-swarm-cronjob:
    image: ghcr.io/crazy-max/swarm-cronjob:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      TZ: ${TZ}
