"""alter_game_table_name_to_product

Revision ID: 589101ada78c
Revises: 22501e4b6ecc
Create Date: 2025-12-30 15:17:30.005949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '589101ada78c'
down_revision: Union[str, Sequence[str], None] = '22501e4b6ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_url'), 'products', ['url'], unique=True)
    op.drop_index(op.f('ix_games_url'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_url'), 'games', ['url'], unique=1)
    op.drop_index(op.f('ix_products_url'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
