"""initial

Revision ID: 5bc9cbd2106b
Revises: 
Create Date: 2026-01-01 16:09:20.336852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5bc9cbd2106b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id', 'namespace')
    )
    op.create_index(op.f('ix_products_namespace'), 'products', ['namespace'], unique=False)
    op.create_index(op.f('ix_products_offer_id'), 'products', ['offer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_offer_id'), table_name='products')
    op.drop_index(op.f('ix_products_namespace'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
