image:
  repository: ghcr.io/nayetdet/gatekeeper
  tag: latest

schedule: "0 15 * * *"
timeZone: America/Fortaleza
env:
  EPIC_GAMES_LOCALE: pt-BR
  EPIC_GAMES_COUNTRY: BR
  TELEGRAM_BOT_ENABLED: "true"

secret:
  enabled: true
  name: gatekeeper

externalSecret:
  enabled: false
  storeName: ""
  refreshInterval: 1h
  remoteKey: gatekeeper

persistence:
  size: 10Gi
  storageClass: &storageClass local-path

resources:
  requests:
    memory: 1Gi
  limits:
    memory: 4Gi

shmSizeLimit: 2Gi

filebrowser:
  enabled: false
  auth:
    enabled: true
  workload:
    main:
      podSpec:
        containers:
          main:
            env:
              FB_NOAUTH: '{{ ternary "false" "noauth" .Values.auth.enabled }}'
  persistence:
    config:
      storageClass: *storageClass
      size: 256Mi
    database:
      storageClass: *storageClass
      size: 256Mi
    data:
      existingClaim: gatekeeper
      readOnly: true
  ingress:
    main:
      enabled: false
      hosts:
        - host: ""
          paths:
            - path: /
