image:
  repository: ghcr.io/nayetdet/gatekeeper
  tag: latest

schedule: "0 15 * * *"
timeZone: America/Fortaleza
env:
  EPIC_GAMES_LOCALE: pt-BR
  EPIC_GAMES_COUNTRY: BR
  TELEGRAM_BOT_ENABLED: "true"

secret:
  enabled: true
  name: gatekeeper

externalSecret:
  enabled: false
  storeName: ""
  refreshInterval: 1h
  remoteKey: gatekeeper

persistence:
  size: 10Gi
  storageClass: ""

resources:
  memoryRequest: 1Gi
  memoryLimit: 4Gi
  shmSizeLimit: 2Gi

sftpgo:
  sftpd:
    enabled: false
  persistence:
    enabled: true
    pvc:
      resources:
        requests:
          storage: 256Mi
  volumes:
    - name: gatekeeper-data
      persistentVolumeClaim:
        claimName: gatekeeper-gatekeeper-data
  volumeMounts:
    - name: gatekeeper-data
      mountPath: /srv/sftpgo/data
  ui:
    ingress:
      enabled: true
      hosts:
        - host: ""
          paths:
            - path: /
              pathType: Prefix
